### ISSUE TITLE
Launch config on *.code-workspace is not appear on the list

### ISSUE THREAD

**Issue by gustitammam** [Quatters/select-and-run-without-debug#6]
I have a `*.code-workspace` file that includes 3 launch configurations, as well as a `.vscode/launch.json` file that contains 2 additional launch configurations. However, this extension only displays the list from the `.vscode/launch.json` file, even though the Debug panel shows a total of 5 launch configurations.

**VSCode Version:** v1.83.1
**Extension Version:** v1.1.2

**Comment by Quatters** [comment]
@gustitammam thanks for the issue! I'll try to fix it soon.

**Comment by Quatters** [comment]
Fixed in 1.1.3.

**Comment by gustitammam** [comment]
Hi @Quatters,

Thank you for the update. However, after updating to version 1.1.3, I'm still encountering issues.

The extension's behavior remains problematic:

1. It exclusively displays launch configurations from the `launch.json` file, resulting in duplicated lines in the list. Moreover, no launch configurations from the workspace appear in the list.
2. Even under conditions where there's no `launch.json` file, the extension still exhibits issues by showing duplicated lines when displaying the launch configurations list from the `*.code-workspace` file.

Here are some specifics about my environment setup:

**VSCode Version:** v1.83.1
**Extension Version:** v1.1.3

<details><summary>Here's the content of my .vscode/launch.json:</summary>
<p>

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "ORun",
      "type": "python",
      "request": "launch",
      "program": "/opt/deploy/odoo",
      "args": [
        "--config=${workspaceFolder}/workdir/conf/odoo.conf",
        "--dev=reload,xml"
      ],
      "console": "integratedTerminal"
    },
    {
      "name": "OUpdate",
      "type": "python",
      "request": "launch",
      "program": "/opt/deploy/odoo-update",
      "args": [
        "--config=${workspaceFolder}/workdir/conf/odoo.conf",
        "--database=********",
        "--if-exists",
        "--ignore-core-addons"
      ],
      "console": "integratedTerminal"
    }
  ]
}
``` 

</p>
</details> 

<details><summary>And here's the content of my *.code-workspace:</summary>
<p>

```
{
  "folders": [
    {
      "path": "."
    }
  ],
  "settings": {
    "remote.autoForwardPorts": false,
    "remote.restoreForwardedPorts": false,
    "launch": {
      "version": "0.2.0",
      "configurations": [
        {
          "name": "Odoo",
          "type": "python",
          "request": "launch",
          "program": "${env:ODOO_BIN}",
          "args": [
            "--config=${workspaceFolder}/workdir/conf/odoo.conf"
          ],
          "console": "integratedTerminal"
        },
        {
          "name": "Odoo Autoreload",
          "type": "python",
          "request": "launch",
          "program": "${env:ODOO_BIN}",
          "args": [
            "--config=${workspaceFolder}/workdir/conf/odoo.conf",
            "--dev=reload,xml"
          ],
          "console": "integratedTerminal"
        },
        {
          "name": "Odoo Update",
          "type": "python",
          "request": "launch",
          "program": "/opt/deploy/odoo-update",
          "args": [
            "--config=${workspaceFolder}/workdir/conf/odoo.conf",
            "--database=${env:ODOO_DB}",
            "--if-exists",
            "--ignore-core-addons"
          ],
          "console": "integratedTerminal"
        },
        {
          "name": "Odoo Makepot",
          "type": "python",
          "request": "launch",
          "program": "/opt/deploy/odoo-makepot",
          "args": [
            "--config=${workspaceFolder}/workdir/conf/odoo.conf",
            "--addons-dir=${workspaceFolder}/workdir/addons",
            "--database=${env:ODOO_DB}",
            "--msgmerge-if-new-pot"
          ],
          "console": "integratedTerminal"
        }
      ]
    }
  }
}
```

</p>
</details> 

**Expected behavior:**
The extension should display the following list:

- **ORun** (from `launch.json`)
- **OUpdate** (from `launch.json`)
- **Odoo** (from `*.code-workspace`)
- **Odoo Autoreload** (from `*.code-workspace`)
- **Odoo Update** (from `*.code-workspace`)
- **Odoo Makepot** (from `*.code-workspace`)

**Actual behavior:**
It currently displays:

- **ORun** (from `launch.json`)
- **OUpdate** (from `launch.json`)
- **ORun** (from `launch.json`)
- **OUpdate** (from `launch.json`)

<details><summary>Secreenshot attached</summary>
<p>

![image](https://github.com/Quatters/select-and-run-without-debug/assets/11481845/f3da4c6c-b424-45e6-bec7-579161338e01)


</p>
</details> 

OR

- **Odoo** (from `*.code-workspace`)
- **Odoo Autoreload** (from `*.code-workspace`)
- **Odoo Update** (from `*.code-workspace`)
- **Odoo Makepot** (from `*.code-workspace`)
- **Odoo** (from `*.code-workspace`)
- **Odoo Autoreload** (from `*.code-workspace`)
- **Odoo Update** (from `*.code-workspace`)
- **Odoo Makepot** (from `*.code-workspace`)

<details><summary>Secreenshot attached</summary>
<p>

![image](https://github.com/Quatters/select-and-run-without-debug/assets/11481845/37366725-d715-41cb-a225-09ae0ca042da)

</p>
</details> 


Thank you for your attention to this matter.

**Comment by Quatters** [comment]
@gustitammam thank you for detailed report. I was able to reproduce these problems. Made a fix and now on my side (with your setup) everything works as expected. Checkout v1.1.4 please.

**Comment by gustitammam** [comment]
Hi @Quatters 

Everything is working perfectly now. 

![image](https://github.com/Quatters/select-and-run-without-debug/assets/11481845/dca9e3fc-71f5-4b25-828b-c9a12627e6ac)


The launch configurations from both the `launch.json` file and the `*.code-workspace` file are showing just like the built-in list on the debug panel.

![image](https://github.com/Quatters/select-and-run-without-debug/assets/11481845/ea7df506-070b-45ab-8154-d307179bd15e)


Thanks a lot!
